import * as ImagePicker from 'expo-image-picker';
import { useRouter } from 'expo-router';
import { ArrowLeft, ImagePlus } from 'lucide-react-native';
import React, { useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Image, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BrandColors, Radius, Shadows, Spacing, Typography } from '../../constants/theme';
import { useSubmitApplication } from '../../hooks/useMuaOnboarding';
import { useMuaStyles } from '../../hooks/useMuaStyles';
import { uploadImage } from '../../services/supabase';
import { getApiError } from '../../services/api';
import { useAuthStore } from '../../store/useAuthStore';
import type { MuaApplicationRequestDto } from '../../types/onboarding';
import { validateMuaOnboarding } from '../../utils/muaOnboarding';

export default function MuaApplyScreen() {
  const router=useRouter(), user=useAuthStore(x=>x.user), submit=useSubmitApplication(), stylesQuery=useMuaStyles();
  const [form,setForm]=useState<MuaApplicationRequestDto>({displayName:user?.name||'',phoneNumber:'',city:'',address:'',bio:'',experienceYears:0,specialization:'',socialLinks:'',avatarUrl:user?.avatarUrl||user?.avatar||'',styleIds:[]});
  const [errors,setErrors]=useState<Record<string,string>>({});
  const scrollRef=useRef<ScrollView>(null);
  const selected=useMemo(()=>new Set(form.styleIds),[form.styleIds]);
  const setField=<K extends keyof MuaApplicationRequestDto>(key:K,value:MuaApplicationRequestDto[K])=>{setForm(current=>({...current,[key]:value}));setErrors(current=>({...current,[key]:'',submit:''}));};
  const pickAvatar=async()=>{const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)return setErrors(current=>({...current,avatarUrl:'Cần quyền truy cập thư viện ảnh.'}));const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.82,allowsEditing:true,aspect:[1,1]});if(!result.canceled&&result.assets[0])setField('avatarUrl',result.assets[0].uri);};
  const save=async()=>{const nextErrors=validateMuaOnboarding(form);setErrors(nextErrors);if(Object.keys(nextErrors).length){const firstMessage=Object.values(nextErrors)[0];scrollRef.current?.scrollTo({y:0,animated:true});Alert.alert('Thông tin chưa hoàn tất',firstMessage);return;}if(submit.isPending)return;try{await submit.mutateAsync({...form,avatarUrl:await uploadImage(form.avatarUrl)});router.replace('/(mua)/dashboard');}catch(error){const message=getApiError(error).message||'Không thể tạo hồ sơ MUA.';setErrors(current=>({...current,submit:message}));Alert.alert('Không thể tạo hồ sơ MUA',message);}};
  const input=(label:string,key:keyof MuaApplicationRequestDto,props:React.ComponentProps<typeof TextInput>={})=><View style={s.group}><Text style={s.label}>{label}</Text><TextInput {...props} value={String(form[key]??'')} onChangeText={value=>setField(key,(key==='experienceYears'?Number(value.replace(/\D/g,'')):value) as never)} placeholderTextColor={BrandColors.textMuted} style={[s.input,props.multiline&&s.textarea,errors[key]&&s.inputError]}/>{errors[key]?<Text style={s.error}>{errors[key]}</Text>:null}</View>;
  return <SafeAreaView style={s.safe} edges={['top','bottom']}><View style={s.header}><TouchableOpacity style={s.icon} onPress={()=>router.back()}><ArrowLeft size={23} color={BrandColors.textDark}/></TouchableOpacity><View style={s.headerCopy}><Text style={s.title}>Trở thành Makeup Artist</Text><Text style={s.subtitle}>Bước đầu · Thông tin MUA</Text></View><View style={s.icon}/></View>
    <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView ref={scrollRef} keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}><View style={s.note}><Text style={s.noteTitle}>Tạo hồ sơ trước, hoàn thiện sau</Text><Text style={s.noteText}>Sau bước này bạn sẽ vào giao diện MUA và dùng checklist “Hoàn thành để nhận booking” để thêm dịch vụ, portfolio, xác minh danh tính và ngân hàng.</Text></View><View style={s.card}><Text style={s.cardTitle}>Thông tin cơ bản</Text>
      <View style={s.group}><Text style={s.label}>Ảnh đại diện</Text><TouchableOpacity style={[s.avatarPicker,errors.avatarUrl&&s.inputError]} onPress={pickAvatar}>{form.avatarUrl?<Image source={{uri:form.avatarUrl}} style={s.avatar}/>:<ImagePlus size={28} color={BrandColors.accentRose}/>}<Text style={s.avatarText}>{form.avatarUrl?'Thay ảnh':'Chọn ảnh đại diện'}</Text></TouchableOpacity>{errors.avatarUrl?<Text style={s.error}>{errors.avatarUrl}</Text>:null}</View>
      {input('Họ tên','displayName',{placeholder:'Nguyễn Thị Linh'})}<View style={s.group}><Text style={s.label}>Email</Text><TextInput editable={false} value={user?.email||''} style={[s.input,s.readonly]}/></View>{input('Số điện thoại','phoneNumber',{placeholder:'0901234567',keyboardType:'phone-pad'})}{input('Địa chỉ','address',{placeholder:'Số nhà, đường, quận/huyện'})}{input('Khu vực hoạt động','city',{placeholder:'TP. Hồ Chí Minh'})}{input('Giới thiệu chuyên môn','bio',{placeholder:'Kinh nghiệm và thế mạnh của bạn...',multiline:true})}{input('Số năm kinh nghiệm','experienceYears',{placeholder:'0',keyboardType:'number-pad'})}
      <View style={s.group}><Text style={s.label}>Phong cách make-up</Text><View style={s.chips}>{stylesQuery.data?.map(item=>{const active=selected.has(item.styleId);return <TouchableOpacity key={item.styleId} onPress={()=>setField('styleIds',active?form.styleIds.filter(id=>id!==item.styleId):[...form.styleIds,item.styleId])} style={[s.chip,active&&s.chipActive]}><Text style={[s.chipText,active&&s.chipTextActive]}>{item.name}</Text></TouchableOpacity>;})}</View>{errors.styleIds?<Text style={s.error}>{errors.styleIds}</Text>:null}</View>{errors.submit?<Text style={s.error}>{errors.submit}</Text>:null}</View></ScrollView>
      <View style={s.footer}><TouchableOpacity disabled={submit.isPending||stylesQuery.isLoading} onPress={save} style={[s.primary,(submit.isPending||stylesQuery.isLoading)&&s.disabled]}>{submit.isPending?<ActivityIndicator color="#FFF"/>:<Text style={s.primaryText}>Tạo hồ sơ MUA</Text>}</TouchableOpacity></View></KeyboardAvoidingView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BrandColors.bgPrimary},header:{minHeight:64,paddingHorizontal:Spacing.md,backgroundColor:'#FFF',flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:BrandColors.borderLight},icon:{width:44,height:44,alignItems:'center',justifyContent:'center'},headerCopy:{flex:1,alignItems:'center'},title:{fontFamily:Typography.bold,fontSize:18,color:BrandColors.textDark},subtitle:{fontFamily:Typography.regular,fontSize:12,color:BrandColors.textMuted,marginTop:2},content:{width:'100%',maxWidth:760,alignSelf:'center',padding:Spacing.base,paddingBottom:Spacing.xl,gap:Spacing.md},note:{padding:Spacing.base,borderRadius:Radius.base,backgroundColor:BrandColors.bgPinkLight,borderWidth:1,borderColor:BrandColors.borderLight},noteTitle:{fontFamily:Typography.bold,fontSize:15,color:BrandColors.textDark},noteText:{fontFamily:Typography.regular,fontSize:13,lineHeight:19,color:BrandColors.textBody,marginTop:5},card:{backgroundColor:'#FFF',borderRadius:Radius.lg,padding:Spacing.base,borderWidth:1,borderColor:BrandColors.borderLight,...Shadows.sm},cardTitle:{fontFamily:Typography.extraBold,fontSize:18,color:BrandColors.textDark},group:{marginTop:Spacing.md},label:{fontFamily:Typography.semiBold,fontSize:14,color:BrandColors.textDark,marginBottom:7},input:{minHeight:50,borderRadius:Radius.md,borderWidth:1,borderColor:BrandColors.borderLight,paddingHorizontal:14,fontFamily:Typography.regular,fontSize:15,color:BrandColors.textDark,backgroundColor:'#FFF'},readonly:{backgroundColor:BrandColors.bgPrimary,color:BrandColors.textMuted},textarea:{minHeight:105,paddingTop:12,textAlignVertical:'top'},inputError:{borderColor:BrandColors.statusCancelled},error:{fontFamily:Typography.regular,fontSize:12,color:BrandColors.statusCancelled,marginTop:5},avatarPicker:{minHeight:82,borderWidth:1,borderColor:BrandColors.borderLight,borderRadius:Radius.md,padding:10,flexDirection:'row',alignItems:'center',gap:12},avatar:{width:60,height:60,borderRadius:30},avatarText:{fontFamily:Typography.bold,color:BrandColors.accentRose},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:13,paddingVertical:10,borderRadius:Radius.full,borderWidth:1,borderColor:BrandColors.borderLight},chipActive:{backgroundColor:BrandColors.accentRose,borderColor:BrandColors.accentRose},chipText:{fontFamily:Typography.medium,color:BrandColors.textBody},chipTextActive:{color:'#FFF'},footer:{backgroundColor:'#FFF',borderTopWidth:1,borderTopColor:BrandColors.borderLight,padding:12},primary:{width:'100%',maxWidth:560,alignSelf:'center',minHeight:52,borderRadius:Radius.md,backgroundColor:BrandColors.accentRose,alignItems:'center',justifyContent:'center'},primaryText:{fontFamily:Typography.bold,color:'#FFF',fontSize:15},disabled:{opacity:.5}});
