import React from 'react';
import {ActivityIndicator,Alert,FlatList,Image,RefreshControl,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {ArrowLeft,CheckCircle2,XCircle} from 'lucide-react-native';
import {useRouter} from 'expo-router';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {adminBankAccountService,PendingBankAccount} from '../../../services/adminBankAccountService';
import {getApiError} from '../../../services/api';
import {BrandColors,Radius,Spacing,Typography} from '../../../constants/theme';

const KEY=['admin','bank-accounts','pending'] as const;
export default function AdminBankAccounts(){const router=useRouter();const qc=useQueryClient();const query=useQuery({queryKey:KEY,queryFn:adminBankAccountService.pending,refetchInterval:10000});const action=useMutation({mutationFn:({item,kind}:{item:PendingBankAccount;kind:'approve'|'reject'})=>kind==='approve'?adminBankAccountService.approve(item):adminBankAccountService.reject(item),onSuccess:()=>qc.invalidateQueries({queryKey:KEY}),onError:e=>Alert.alert('Không thể cập nhật',getApiError(e).message)});const confirm=(item:PendingBankAccount,kind:'approve'|'reject')=>Alert.alert(kind==='approve'?'Duyệt tài khoản?':'Từ chối tài khoản?',`${item.bankName||item.bankCode} · ${item.accountNumber}\n${item.accountHolderName}`,[{text:'Hủy',style:'cancel'},{text:kind==='approve'?'Duyệt':'Từ chối',style:kind==='reject'?'destructive':'default',onPress:()=>action.mutate({item,kind})}]);return <SafeAreaView style={s.safe}><View style={s.header}><TouchableOpacity style={s.back} onPress={()=>router.back()}><ArrowLeft size={23}/></TouchableOpacity><View><Text style={s.title}>Duyệt tài khoản nhận tiền</Text><Text style={s.sub}>Customer và MUA thêm lần đầu</Text></View></View>{query.isLoading?<ActivityIndicator style={{marginTop:50}} color={BrandColors.accentRose}/>:<FlatList data={query.data||[]} keyExtractor={x=>`${x.ownerType}-${x.id}`} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={()=>query.refetch()}/>} contentContainerStyle={s.list} ListEmptyComponent={<Text style={s.empty}>Không có tài khoản chờ duyệt.</Text>} renderItem={({item})=><View style={s.card}><View style={s.top}><View><Text style={s.owner}>{item.ownerName||item.ownerId}</Text><Text style={s.role}>{item.ownerType==='MUA'?'MUA':'Customer'}</Text></View><Text style={s.time}>{new Date(item.createdAt).toLocaleString('vi-VN')}</Text></View><Text style={s.bank}>{item.bankName||item.bankCode} · {item.method}</Text><Text style={s.account}>{item.accountNumber}</Text><Text style={s.holder}>{item.accountHolderName}</Text>{item.qrCodeUrl?<Image source={{uri:item.qrCodeUrl}} style={s.qr} resizeMode="contain"/>:null}<Text style={s.warning}>Đối chiếu QR, ngân hàng, số tài khoản và tên trước khi duyệt.</Text><View style={s.actions}><TouchableOpacity style={s.reject} disabled={action.isPending} onPress={()=>confirm(item,'reject')}><XCircle size={19} color={BrandColors.statusCancelled}/><Text style={s.rejectText}>Từ chối</Text></TouchableOpacity><TouchableOpacity style={s.approve} disabled={action.isPending} onPress={()=>confirm(item,'approve')}><CheckCircle2 size={19} color="#FFF"/><Text style={s.approveText}>Duyệt</Text></TouchableOpacity></View></View>}/>}</SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BrandColors.bgPrimary},header:{flexDirection:'row',alignItems:'center',gap:10,padding:Spacing.md},back:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontFamily:Typography.bold,fontSize:20,color:BrandColors.textDark},sub:{fontFamily:Typography.regular,fontSize:12,color:BrandColors.textSecondary,marginTop:2},list:{width:'100%',maxWidth:760,alignSelf:'center',padding:Spacing.base,paddingBottom:Spacing.xxl},empty:{textAlign:'center',marginTop:60,fontFamily:Typography.regular,color:BrandColors.textMuted},card:{backgroundColor:'#FFF',borderRadius:Radius.lg,padding:Spacing.base,marginBottom:Spacing.md,borderWidth:1,borderColor:BrandColors.borderLight},top:{flexDirection:'row',justifyContent:'space-between',gap:12},owner:{fontFamily:Typography.bold,fontSize:16,color:BrandColors.textDark},role:{fontFamily:Typography.bold,fontSize:10,color:BrandColors.accentRose,marginTop:3},time:{fontFamily:Typography.regular,fontSize:11,color:BrandColors.textMuted},bank:{fontFamily:Typography.semiBold,color:BrandColors.textBody,marginTop:14},account:{fontFamily:Typography.extraBold,fontSize:21,color:BrandColors.textDark,marginTop:5},holder:{fontFamily:Typography.semiBold,color:BrandColors.textSecondary,marginTop:3},qr:{width:220,height:220,alignSelf:'center',marginTop:12},warning:{fontFamily:Typography.regular,fontSize:12,color:'#9A6700',backgroundColor:'#FFF4CE',padding:10,borderRadius:Radius.sm,marginTop:10},actions:{flexDirection:'row',gap:10,marginTop:14},reject:{flex:1,minHeight:48,flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:BrandColors.statusCancelled,borderRadius:Radius.full},rejectText:{fontFamily:Typography.bold,color:BrandColors.statusCancelled},approve:{flex:1,minHeight:48,flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center',backgroundColor:BrandColors.statusConfirmed,borderRadius:Radius.full},approveText:{fontFamily:Typography.bold,color:'#FFF'}});
