import {beforeEach,describe,expect,it,jest} from '@jest/globals';
jest.mock('../api',()=>({api:{post:jest.fn(),put:jest.fn(),get:jest.fn(),delete:jest.fn()}}));
import {api} from '../api';
import {bankAccountService} from '../bankAccountService';
import {adminBankAccountService} from '../adminBankAccountService';
const post=api.post as jest.Mock<any>;const put=api.put as jest.Mock<any>;const get=api.get as jest.Mock<any>;
const response={id:'bank-1',bankCode:'VCB',bankBin:'970436',bankName:'VCB',maskedAccountNumber:'**1111',accountHolderName:'A',isDefault:false,isActive:true,verificationStatus:'PENDING_ADMIN',method:'BANK',activatedAt:null,isCoolingDown:false,isUsable:false,canReceiveMoney:false};
const draft={bankCode:'VCB',bankBin:'970436',bankName:'VCB',accountNumber:'111111',accountHolderName:'A',method:'BANK' as const};
const request={...draft,otp:'123456'};
describe('shared bank account API',()=>{beforeEach(()=>{post.mockReset();put.mockReset();get.mockReset();post.mockResolvedValue({data:response});put.mockResolvedValue({data:response});get.mockResolvedValue({data:[response]});});
it('Customer and MUA modes read the same list endpoint',async()=>{await bankAccountService.getAll();await bankAccountService.getAll();expect(get).toHaveBeenNthCalledWith(1,'/bank-accounts');expect(get).toHaveBeenNthCalledWith(2,'/bank-accounts');});
it('requests OTP through add and update endpoints with the exact draft',async()=>{post.mockResolvedValue({data:{maskedEmail:'u***@example.com',expiresInSeconds:300,resendAfterSeconds:60}});await bankAccountService.requestOtp(draft);await bankAccountService.requestOtp(draft,'bank-1');expect(post).toHaveBeenNthCalledWith(1,'/bank-accounts/request-otp',draft);expect(post).toHaveBeenNthCalledWith(2,'/bank-accounts/bank-1/request-otp',draft);});
it('creates through the shared endpoint with OTP and no password',async()=>{await bankAccountService.add(request);expect(post).toHaveBeenCalledWith('/bank-accounts',request);expect(post).not.toHaveBeenCalledWith('/bank-accounts',expect.objectContaining({currentPassword:expect.anything()}));});
it('updates through the shared endpoint with the same payload and OTP',async()=>{await bankAccountService.update('bank-1',request);expect(put).toHaveBeenCalledWith('/bank-accounts/bank-1',request);});
it('sets default using password only',async()=>{await bankAccountService.setDefault('bank-1','secret1');expect(post).toHaveBeenCalledWith('/bank-accounts/bank-1/set-default',{currentPassword:'secret1'});});
it('admin approve and reject use owner-type-free endpoints',async()=>{const item={...response,method:'BANK' as const,ownerId:'u',accountNumber:'111111',createdAt:'2026-09-30'};await adminBankAccountService.approve(item);await adminBankAccountService.reject(item);expect(post).toHaveBeenNthCalledWith(1,'/admin/bank-accounts/bank-1/approve',{});expect(post).toHaveBeenNthCalledWith(2,'/admin/bank-accounts/bank-1/reject',{});});});
