import React, { useMemo, useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity } from 'react-native';
import { ChevronLeft, ChevronRight } from 'lucide-react-native';
import { router } from 'expo-router';
import { BookingDto } from '../../types/booking';
import { BrandColors, Radius, Spacing, Typography } from '../../constants/theme';

const WEEKDAYS = ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'CN'];
const isoDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;

export function InternalBookingCalendar({ bookings, viewAs }: { bookings: BookingDto[]; viewAs: 'customer' | 'mua' }) {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [selectedDate, setSelectedDate] = useState(() => isoDate(new Date()));
  const visibleBookings = useMemo(() => bookings.filter(b => ['CONFIRMED', 'IN_PROGRESS', 'WAITING_CUSTOMER'].includes(b.status)), [bookings]);
  const days = useMemo(() => { const first = new Date(month.getFullYear(), month.getMonth(), 1); const offset = (first.getDay() + 6) % 7; return Array.from({ length: 42 }, (_, i) => new Date(month.getFullYear(), month.getMonth(), i - offset + 1)); }, [month]);
  const selectedBookings = visibleBookings.filter(b => b.date === selectedDate).sort((a, b) => a.time.localeCompare(b.time));
  return <View>
    <View style={styles.monthHeader}><TouchableOpacity onPress={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}><ChevronLeft color={BrandColors.textDark} /></TouchableOpacity><Text style={styles.monthTitle}>THÁNG {month.getMonth() + 1} - {month.getFullYear()}</Text><TouchableOpacity onPress={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}><ChevronRight color={BrandColors.textDark} /></TouchableOpacity></View>
    <View style={styles.weekRow}>{WEEKDAYS.map(day => <Text key={day} style={styles.weekday}>{day}</Text>)}</View>
    <View style={styles.grid}>{days.map(day => { const key = isoDate(day); const inMonth = day.getMonth() === month.getMonth(); const has = visibleBookings.some(b => b.date === key); const selected = key === selectedDate; return <TouchableOpacity key={key} style={styles.dayCell} onPress={() => { setSelectedDate(key); if (!inMonth) setMonth(new Date(day.getFullYear(), day.getMonth(), 1)); }}><View style={[styles.dayCircle, selected && styles.daySelected]}><Text style={[styles.dayText, !inMonth && styles.dayMuted, selected && styles.daySelectedText]}>{day.getDate()}</Text></View>{has && <View style={styles.dot} />}</TouchableOpacity>; })}</View>
    <Text style={styles.selectedTitle}>{selectedDate.split('-').reverse().join('/')}</Text>
    {selectedBookings.length === 0 ? <Text style={styles.empty}>Không có lịch đã xác nhận trong ngày này.</Text> : selectedBookings.map(booking => { const duration = booking.services.reduce((sum, s) => sum + s.durationMinutes * s.participantsCount, 0); const [h, m] = booking.time.split(':').map(Number); const end = new Date(2000, 0, 1, h, m + duration); return <View key={booking.id} style={styles.bookingCard}><Text style={styles.bookingTime}>{booking.time} - {String(end.getHours()).padStart(2, '0')}:{String(end.getMinutes()).padStart(2, '0')}</Text><Text style={styles.person}>👤 {viewAs === 'mua' ? booking.customer.name : booking.mua.name}</Text><Text style={styles.service}>💄 {booking.services.map(s => s.name).join(', ')}</Text>{!!booking.address && <Text style={styles.address}>📍 {booking.address}</Text>}<TouchableOpacity style={styles.detailButton} onPress={() => router.push(viewAs === 'mua' ? `/(mua)/mua-booking/${booking.id}` : `/booking/${booking.id}`)}><Text style={styles.detailText}>Xem booking</Text></TouchableOpacity></View>; })}
  </View>;
}

const styles = StyleSheet.create({ monthHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:Spacing.md},monthTitle:{fontFamily:Typography.bold,fontSize:17,color:BrandColors.textDark},weekRow:{flexDirection:'row'},weekday:{width:'14.285%',textAlign:'center',fontFamily:Typography.semiBold,color:BrandColors.textMuted,paddingVertical:8},grid:{flexDirection:'row',flexWrap:'wrap'},dayCell:{width:'14.285%',height:48,alignItems:'center'},dayCircle:{width:32,height:32,borderRadius:16,alignItems:'center',justifyContent:'center'},daySelected:{backgroundColor:BrandColors.accentRose},dayText:{fontFamily:Typography.medium,color:BrandColors.textDark},dayMuted:{color:'#C7C7C7'},daySelectedText:{color:'#FFF'},dot:{width:5,height:5,borderRadius:3,backgroundColor:BrandColors.accentRose,marginTop:2},selectedTitle:{fontFamily:Typography.bold,fontSize:17,color:BrandColors.textDark,borderTopWidth:1,borderTopColor:BrandColors.borderLight,paddingTop:Spacing.md,marginTop:Spacing.sm},empty:{fontFamily:Typography.regular,color:BrandColors.textMuted,paddingVertical:Spacing.lg,textAlign:'center'},bookingCard:{backgroundColor:'#FFF',borderRadius:Radius.lg,padding:Spacing.md,marginTop:Spacing.md,borderWidth:1,borderColor:BrandColors.borderLight},bookingTime:{fontFamily:Typography.bold,color:BrandColors.accentRose,marginBottom:8},person:{fontFamily:Typography.semiBold,color:BrandColors.textDark,marginBottom:5},service:{fontFamily:Typography.medium,color:BrandColors.textDark,marginBottom:5},address:{fontFamily:Typography.regular,color:BrandColors.textMuted,marginBottom:10},detailButton:{alignSelf:'flex-start',backgroundColor:BrandColors.accentRose,paddingHorizontal:14,paddingVertical:8,borderRadius:Radius.full},detailText:{fontFamily:Typography.bold,color:'#FFF'} });
