import React,{useState} from 'react';
import { Image,RefreshControl,ScrollView,StyleSheet,Text,TouchableOpacity,useWindowDimensions,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { ArrowLeft,ChevronRight,Clock3,MapPin,Users } from 'lucide-react-native';
import { useAdminMuaApplications } from '../../../hooks/useAdminMuaApplications';
import { AdminEmptyState,AdminErrorState,AdminLoadingState } from '../../../components/admin/AdminStates';
import { BrandColors,Radius,Shadows,Spacing,Typography } from '../../../constants/theme';

const filters=[['PendingReview','Chờ duyệt'],['Approved','Đã duyệt'],['Rejected','Từ chối'],['','Tất cả']] as const;
const labels:Record<string,string>={PendingReview:'Chờ duyệt',Approved:'Đã duyệt',Rejected:'Từ chối',Draft:'Bản nháp'};
const colors:Record<string,[string,string]>={PendingReview:['#9A6700','#FFF4CE'],Approved:['#067647','#ECFDF3'],Rejected:['#B42318','#FEF3F2'],Draft:['#475467','#F2F4F7']};
export default function AdminMuaApplications(){
 const router=useRouter();const {width}=useWindowDimensions();const wide=width>=760;const [status,setStatus]=useState('PendingReview');const q=useAdminMuaApplications(status);
 return <SafeAreaView style={s.safe} edges={['top']}><View style={s.shell}><View style={s.header}><TouchableOpacity style={s.back} onPress={()=>router.back()}><ArrowLeft size={22} color={BrandColors.textDark}/></TouchableOpacity><View style={s.headerCopy}><Text style={s.eyebrow}>KIỂM DUYỆT ĐỐI TÁC</Text><Text style={s.title}>Hồ sơ Makeup Artist</Text></View><View style={s.count}><Users size={17} color={BrandColors.accentRose}/><Text style={s.countText}>{q.data?.length??0}</Text></View></View>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{filters.map(([key,label])=><TouchableOpacity key={label} onPress={()=>setStatus(key)} style={[s.filter,status===key&&s.filterActive]}><Text style={[s.filterText,status===key&&s.filterTextActive]}>{label}</Text></TouchableOpacity>)}</ScrollView>
 {q.isLoading?<AdminLoadingState message="Đang tải hồ sơ MUA..."/>:q.isError?<AdminErrorState message="Không thể tải danh sách hồ sơ." onRetry={()=>q.refetch()} retrying={q.isFetching}/>:!q.data?.length?<AdminEmptyState title="Không có hồ sơ" message="Không có hồ sơ nào trong trạng thái này."/>:<ScrollView refreshControl={<RefreshControl refreshing={q.isRefetching} onRefresh={q.refetch}/>} contentContainerStyle={[s.grid,wide&&s.gridWide]}>{q.data.map(x=>{const c=colors[x.verificationStatus]||colors.Draft;return <TouchableOpacity key={x.muaId} style={[s.card,wide&&s.cardWide]} activeOpacity={.82} onPress={()=>router.push(`/(admin)/mua-applications/${x.muaId}` as any)}><View style={s.cardTop}>{x.avatarUrl?<Image source={{uri:x.avatarUrl}} style={s.avatar}/>:<View style={s.avatarFallback}><Text style={s.initial}>{x.fullName.slice(0,1).toUpperCase()}</Text></View>}<View style={s.person}><Text style={s.name} numberOfLines={1}>{x.fullName}</Text><View style={s.location}><MapPin size={14} color={BrandColors.textMuted}/><Text style={s.meta}>{x.city||'Chưa cập nhật khu vực'}</Text></View></View><View style={[s.badge,{backgroundColor:c[1]}]}><Text style={[s.badgeText,{color:c[0]}]}>{labels[x.verificationStatus]||x.verificationStatus}</Text></View></View><View style={s.metrics}><Metric value={`${x.completionPercentage}%`} label="Hoàn thiện"/><Metric value={String(x.activeServiceCount)} label="Dịch vụ"/><Metric value={String(x.publicPortfolioImageCount)} label="Ảnh"/></View><View style={s.cardBottom}><View style={s.date}><Clock3 size={14} color={BrandColors.textMuted}/><Text style={s.dateText}>{x.submittedAt?`Gửi ${new Date(x.submittedAt).toLocaleDateString('vi-VN')}`:'Chưa gửi duyệt'}</Text></View><View style={s.open}><Text style={s.openText}>Xem hồ sơ</Text><ChevronRight size={17} color={BrandColors.accentRose}/></View></View></TouchableOpacity>})}</ScrollView>}</View></SafeAreaView>
}
function Metric({value,label}:{value:string;label:string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BrandColors.bgPrimary},shell:{flex:1,width:'100%',maxWidth:1120,alignSelf:'center'},header:{minHeight:82,paddingHorizontal:Spacing.base,flexDirection:'row',alignItems:'center',gap:12},back:{width:44,height:44,borderRadius:22,backgroundColor:'#FFF',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:BrandColors.borderLight},headerCopy:{flex:1},eyebrow:{fontFamily:Typography.bold,fontSize:10,letterSpacing:1.2,color:BrandColors.accentRose},title:{fontFamily:Typography.extraBold,fontSize:23,color:BrandColors.textDark,marginTop:2},count:{height:36,minWidth:54,paddingHorizontal:10,borderRadius:Radius.full,backgroundColor:BrandColors.bgPink,flexDirection:'row',gap:5,alignItems:'center',justifyContent:'center'},countText:{fontFamily:Typography.bold,color:BrandColors.accentRose},filters:{paddingHorizontal:Spacing.base,paddingBottom:Spacing.md,gap:8},filter:{height:40,paddingHorizontal:16,borderRadius:Radius.full,backgroundColor:'#FFF',borderWidth:1,borderColor:BrandColors.borderLight,justifyContent:'center'},filterActive:{backgroundColor:BrandColors.textDark,borderColor:BrandColors.textDark},filterText:{fontFamily:Typography.semiBold,color:BrandColors.textBody},filterTextActive:{color:'#FFF'},grid:{padding:Spacing.base,paddingTop:2,paddingBottom:Spacing.xxl,gap:12},gridWide:{flexDirection:'row',flexWrap:'wrap'},card:{backgroundColor:'#FFF',borderRadius:Radius.lg,padding:Spacing.base,borderWidth:1,borderColor:BrandColors.borderLight,...Shadows.sm},cardWide:{width:'48.9%'},cardTop:{flexDirection:'row',alignItems:'center'},avatar:{width:52,height:52,borderRadius:18},avatarFallback:{width:52,height:52,borderRadius:18,backgroundColor:BrandColors.bgPink,alignItems:'center',justifyContent:'center'},initial:{fontFamily:Typography.extraBold,fontSize:20,color:BrandColors.accentRose},person:{flex:1,marginLeft:12},name:{fontFamily:Typography.bold,fontSize:16,color:BrandColors.textDark},location:{flexDirection:'row',alignItems:'center',gap:3,marginTop:4},meta:{fontFamily:Typography.regular,fontSize:12,color:BrandColors.textMuted},badge:{paddingHorizontal:9,paddingVertical:5,borderRadius:Radius.full},badgeText:{fontFamily:Typography.bold,fontSize:11},metrics:{flexDirection:'row',backgroundColor:'#FAF8F9',borderRadius:Radius.md,marginTop:14,paddingVertical:11},metric:{flex:1,alignItems:'center',borderRightWidth:1,borderRightColor:BrandColors.borderDivider},metricValue:{fontFamily:Typography.extraBold,fontSize:16,color:BrandColors.textDark},metricLabel:{fontFamily:Typography.regular,fontSize:11,color:BrandColors.textMuted,marginTop:2},cardBottom:{flexDirection:'row',alignItems:'center',marginTop:13},date:{flex:1,flexDirection:'row',alignItems:'center',gap:5},dateText:{fontFamily:Typography.regular,fontSize:12,color:BrandColors.textMuted},open:{flexDirection:'row',alignItems:'center'},openText:{fontFamily:Typography.bold,fontSize:12,color:BrandColors.accentRose}});
