import React from 'react';
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ArrowLeft, ChevronRight } from 'lucide-react-native';
import { useRouter } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { refundService } from '../../../services/refundService';
import { BrandColors, Radius, Spacing, Typography } from '../../../constants/theme';

export default function AdminRefunds(){const router=useRouter();const query=useQuery({queryKey:['admin','refunds'],queryFn:refundService.getAdminQueue});return <SafeAreaView style={styles.safe}><View style={styles.header}><TouchableOpacity style={styles.back} onPress={()=>router.back()}><ArrowLeft size={23} color={BrandColors.textDark}/></TouchableOpacity><View><Text style={styles.title}>Hoàn tiền customer</Text><Text style={styles.sub}>Hàng đợi cần xử lý và đối soát</Text></View></View>{query.isLoading?<ActivityIndicator style={{marginTop:40}} color={BrandColors.accentPink}/>:<FlatList data={query.data||[]} keyExtractor={x=>x.refundId} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={()=>query.refetch()}/>} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>Không có refund cần xử lý.</Text>} renderItem={({item})=><TouchableOpacity style={styles.card} onPress={()=>router.push({pathname:'/(admin)/refunds/[id]',params:{id:item.refundId}} as any)}><View style={styles.row}><Text style={styles.amount}>{item.amount.toLocaleString('vi-VN')}đ</Text><Text style={styles.status}>{label(item.status)}</Text></View><Text style={styles.name}>{item.customerName||'Customer'}</Text><Text style={styles.meta}>{item.destinationBankName||item.destinationBankBin||'Chưa có tài khoản'} · {item.maskedDestinationAccountNumber||'Cần bổ sung'}</Text><View style={styles.row}><Text style={styles.date}>{new Date(item.createdAt).toLocaleString('vi-VN')}</Text><ChevronRight size={18} color={BrandColors.textMuted}/></View></TouchableOpacity>}/>}</SafeAreaView>}
const label=(s:string)=>({PENDING:'Chờ tiếp nhận',MANUAL_ACTION_REQUIRED:'Cần xử lý',PROCESSING:'Đang xử lý',FAILED:'Thất bại',AWAITING_DESTINATION:'Chờ tài khoản'}[s]||s);
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BrandColors.bgPrimary},header:{flexDirection:'row',alignItems:'center',gap:10,padding:Spacing.md},back:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontFamily:Typography.extraBold,fontSize:21,color:BrandColors.textDark},sub:{fontFamily:Typography.regular,fontSize:12,color:BrandColors.textSecondary},list:{padding:Spacing.base,paddingBottom:Spacing.xxl},empty:{textAlign:'center',color:BrandColors.textMuted,marginTop:50},card:{backgroundColor:'#FFF',padding:Spacing.base,borderRadius:Radius.base,borderWidth:1,borderColor:BrandColors.borderLight,marginBottom:Spacing.sm},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},amount:{fontFamily:Typography.extraBold,fontSize:20,color:BrandColors.textDark},status:{fontFamily:Typography.bold,fontSize:12,color:BrandColors.accentPink},name:{fontFamily:Typography.bold,color:BrandColors.textDark,marginTop:12},meta:{fontFamily:Typography.regular,fontSize:13,color:BrandColors.textSecondary,marginTop:3,marginBottom:12},date:{fontFamily:Typography.regular,fontSize:11,color:BrandColors.textMuted}});
