import { useAuthStore } from '../store/useAuthStore';
import BankAccountsScreen from './(mua)/bank-accounts';
import React, { useRef, useState } from 'react';
import { ActivityIndicator, FlatList, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ArrowLeft, Building2, CheckCircle2, Pencil, Plus, Star, Trash2 } from 'lucide-react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { refundService } from '../services/refundService';
import { getApiError } from '../services/api';
import { BrandColors, Radius, Spacing, Typography } from '../constants/theme';
import { ConfirmDialog } from '../components/common/ConfirmDialog';
import { FeedbackDialog } from '../components/common/FeedbackDialog';
import { BankDefaultPasswordModal } from '../components/bank/BankDefaultPasswordModal';
import { canOfferBankDefault, getBankAccountErrorMessage, getBankAccountPresentation, isBankAccountSelectable, isEffectiveBankDefault } from '../utils/bankAccountStatus';
import { useBankAccounts, useDeleteBankAccount, useSetDefaultBankAccount } from '../hooks/useBankAccounts';
import type { BankAccount } from '../types/bankAccount';

const securityStyles=StyleSheet.create({badge:{fontFamily:Typography.bold,fontSize:10,color:'#9A6700',backgroundColor:'#FFF4CE',paddingHorizontal:8,paddingVertical:3,borderRadius:Radius.full},text:{fontFamily:Typography.regular,fontSize:11,color:'#9A6700',marginTop:5}});

function RefundDestinationScreen(){
  const router=useRouter();const queryClient=useQueryClient();const submitLock=useRef(false);
  const {refundId,bookingId}=useLocalSearchParams<{refundId?:string;bookingId?:string}>();
  const [deleteId,setDeleteId]=useState<string|null>(null);const [defaultId,setDefaultId]=useState<string|null>(null);
  const [feedback,setFeedback]=useState<{title:string;message:string;error?:boolean;navigate?:boolean}|null>(null);
  const accounts=useBankAccounts();
  const assign=useMutation({mutationFn:(bankAccountId:string)=>refundService.setDestination(String(refundId),bankAccountId),onSuccess:()=>{void queryClient.invalidateQueries({queryKey:['customer-refund',refundId]});void queryClient.invalidateQueries({queryKey:['customer-refunds']});void queryClient.invalidateQueries({queryKey:['bookingDetail',bookingId]});void queryClient.invalidateQueries({queryKey:['userBookings']});setFeedback({title:'Đã chọn tài khoản',message:'Khoản hoàn đã được đưa vào hàng đợi xử lý.',navigate:true});},onError:error=>{const value=getApiError(error);setFeedback({title:'Không thể cập nhật',message:getBankAccountErrorMessage(value.code,value.message),error:true});}});
  const remove=useDeleteBankAccount();
  const setDefault=useSetDefaultBankAccount();
  const openCreate=()=>router.push({pathname:'/refund-bank-account-form',params:{refundId,bookingId}} as never);
  const openEdit=(item:BankAccount)=>router.push({pathname:'/refund-bank-account-form',params:{id:item.id,bankBin:item.bankBin,bankName:item.bankName||'',holder:item.accountHolderName,method:item.method,financialQrMediaId:item.financialQrMediaId}} as never);
  const confirmDefault=async(password:string,otp?:string)=>{if(!defaultId||setDefault.isPending||submitLock.current)return;submitLock.current=true;try{await setDefault.mutateAsync({id:defaultId,currentPassword:password,otp});setDefaultId(null);setFeedback({title:'Đã đặt mặc định',message:'Tài khoản nhận tiền mặc định đã được cập nhật.'});}catch(error){const value=getApiError(error);setFeedback({title:'Không thể đặt mặc định',message:getBankAccountErrorMessage(value.code,value.message),error:true});}finally{submitLock.current=false;}};
  return <SafeAreaView style={styles.safe} edges={['top']}>
    <View style={styles.header}><TouchableOpacity style={styles.icon} onPress={()=>router.back()}><ArrowLeft size={23} color={BrandColors.textDark}/></TouchableOpacity><Text style={styles.title}>Tài khoản nhận hoàn tiền</Text><TouchableOpacity style={styles.icon} onPress={openCreate}><Plus size={23} color={BrandColors.accentRose}/></TouchableOpacity></View>
    {refundId?<View style={styles.notice}><Text style={styles.noticeText}>Chọn tài khoản có thể nhận khoản hoàn này.</Text></View>:null}
    {accounts.isLoading?<ActivityIndicator style={{marginTop:40}} color={BrandColors.accentRose}/>:accounts.isError?<Text style={styles.error}>{getApiError(accounts.error).message}</Text>:<FlatList data={accounts.data||[]} keyExtractor={item=>item.id} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><Building2 size={38} color={BrandColors.textMuted}/><Text style={styles.emptyTitle}>Chưa có tài khoản nhận tiền</Text><Text style={styles.emptyText}>Thêm tài khoản ngân hàng chính chủ để nhận tiền hoàn.</Text><TouchableOpacity style={styles.add} onPress={openCreate}><Text style={styles.addText}>Thêm tài khoản</Text></TouchableOpacity></View>} renderItem={({item})=>{const state=getBankAccountPresentation(item);const selectable=isBankAccountSelectable(item);const effectiveDefault=isEffectiveBankDefault(item);return <TouchableOpacity style={[styles.card,refundId&&!selectable&&styles.cardDisabled]} onPress={()=>refundId&&selectable&&assign.mutate(item.id)} disabled={assign.isPending||Boolean(refundId&&!selectable)} activeOpacity={refundId?.75:1}><View style={styles.copy}><View style={styles.row}><Text style={styles.bank}>{item.bankName||item.bankBin}</Text>{effectiveDefault?<Text style={styles.defaultBadge}>Mặc định</Text>:null}{!selectable?<Text style={securityStyles.badge}>Chưa khả dụng</Text>:null}</View><Text style={styles.number}>{item.maskedAccountNumber}</Text><Text style={styles.holder}>{item.accountHolderName}</Text><Text style={[securityStyles.text,selectable&&styles.usable]}>{state.label}</Text>{!refundId&&canOfferBankDefault(item)?<TouchableOpacity style={styles.defaultButton} onPress={()=>setDefaultId(item.id)}><Star size={15} color={BrandColors.accentRose}/><Text style={styles.defaultButtonText}>Đặt làm mặc định</Text></TouchableOpacity>:null}</View>{refundId?<CheckCircle2 size={22} color={selectable?BrandColors.accentRose:BrandColors.textMuted}/>:<><TouchableOpacity style={styles.action} onPress={()=>openEdit(item)}><Pencil size={18} color={BrandColors.accentRose}/></TouchableOpacity><TouchableOpacity style={styles.action} onPress={()=>setDeleteId(item.id)}><Trash2 size={19} color={BrandColors.statusCancelled}/></TouchableOpacity></>}</TouchableOpacity>;}}/>}
    <ConfirmDialog visible={Boolean(deleteId)} title="Xóa tài khoản" message="Việc ngừng sử dụng không thay đổi khoản chi trả đã bắt đầu. Các khoản hoàn tiền chưa xử lý có thể yêu cầu chọn lại tài khoản." confirmLabel="Xóa" destructive loading={remove.isPending} onCancel={()=>setDeleteId(null)} onConfirm={()=>{if(deleteId)remove.mutate(deleteId,{onSuccess:()=>{setDeleteId(null);setFeedback({title:'Đã xóa tài khoản',message:'Tài khoản không còn được dùng cho giao dịch mới.'});},onError:error=>setFeedback({title:'Không thể xóa',message:getApiError(error).message,error:true})});}}/>
    <BankDefaultPasswordModal accountId={defaultId||undefined} visible={Boolean(defaultId)} loading={setDefault.isPending} onCancel={()=>setDefaultId(null)} onSubmit={confirmDefault}/>
    <FeedbackDialog visible={Boolean(feedback)} title={feedback?.title||''} message={feedback?.message||''} error={feedback?.error} buttonLabel={feedback?.navigate?'Xem hoàn tiền':'Đóng'} onClose={()=>{const navigate=feedback?.navigate;setFeedback(null);if(navigate)router.replace(`/refund/${refundId}` as never);}}/>
  </SafeAreaView>;
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BrandColors.bgPrimary},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:Spacing.md},icon:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontFamily:Typography.bold,fontSize:20,color:BrandColors.textDark},notice:{marginHorizontal:Spacing.base,backgroundColor:BrandColors.bgPink,padding:Spacing.md,borderRadius:Radius.md},noticeText:{fontFamily:Typography.semiBold,fontSize:13,color:BrandColors.textBody},list:{padding:Spacing.base,flexGrow:1},card:{flexDirection:'row',alignItems:'center',backgroundColor:'#FFF',borderWidth:1,borderColor:BrandColors.borderLight,borderRadius:Radius.md,padding:Spacing.md,marginBottom:Spacing.sm},cardDisabled:{opacity:.58},copy:{flex:1},usable:{color:BrandColors.statusConfirmed},row:{flexDirection:'row',alignItems:'center',gap:8},bank:{fontFamily:Typography.bold,fontSize:16,color:BrandColors.textDark},defaultBadge:{fontFamily:Typography.bold,fontSize:10,color:BrandColors.statusConfirmed,backgroundColor:BrandColors.statusConfirmedBg,paddingHorizontal:8,paddingVertical:3,borderRadius:Radius.full},number:{fontFamily:Typography.bold,fontSize:15,color:BrandColors.textBody,marginTop:7},holder:{fontFamily:Typography.regular,fontSize:12,color:BrandColors.textSecondary,marginTop:3},defaultButton:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:6,marginTop:10,paddingHorizontal:12,paddingVertical:8,borderRadius:Radius.full,backgroundColor:BrandColors.bgPinkLight},defaultButtonText:{fontFamily:Typography.bold,fontSize:12,color:BrandColors.accentRose},action:{width:42,height:42,alignItems:'center',justifyContent:'center'},empty:{alignItems:'center',justifyContent:'center',paddingTop:80,paddingHorizontal:Spacing.xl},emptyTitle:{fontFamily:Typography.bold,fontSize:17,color:BrandColors.textDark,marginTop:Spacing.md},emptyText:{fontFamily:Typography.regular,color:BrandColors.textMuted,textAlign:'center',marginTop:5,marginBottom:Spacing.md},add:{backgroundColor:BrandColors.accentRose,borderRadius:Radius.full,paddingHorizontal:20,paddingVertical:12},addText:{fontFamily:Typography.bold,color:'#FFF'},error:{margin:Spacing.base,padding:Spacing.md,color:BrandColors.statusCancelled,backgroundColor:BrandColors.statusCancelledBg,borderRadius:Radius.md}});

export default function ReviewAwareRefundDestination(){const review=useAuthStore(state=>state.user?.isDemoAccount===true);return review?<BankAccountsScreen/>:<RefundDestinationScreen/>;}
