import { act, renderHook } from '@testing-library/react-native';
import { useBankAccountOtpFlow } from '../useBankAccountOtpFlow';
const mockRequest=jest.fn(),mockAdd=jest.fn(),mockUpdate=jest.fn();
jest.mock('../useBankAccounts',()=>({useRequestBankAccountOtp:()=>({mutateAsync:mockRequest}),useAddBankAccount:()=>({mutateAsync:mockAdd}),useUpdateBankAccount:()=>({mutateAsync:mockUpdate})}));
const draft={method:'MOMO' as const,bankCode:'MOMO',bankBin:'MOMO',bankName:'MoMo',accountNumber:'0300000000',accountHolderName:'TEST USER',financialQrAction:'UNCHANGED' as const,financialQrMediaId:'qr-a'};
beforeEach(()=>{jest.clearAllMocks();mockRequest.mockResolvedValue({maskedEmail:'u***@example.test'});});
it('changing QR invalidates confirmation immediately',async()=>{const x=await renderHook<ReturnType<typeof useBankAccountOtpFlow>,{value:typeof draft}>(({value})=>useBankAccountOtpFlow('A',value),{initialProps:{value:draft}});await act(async()=>{await x.result.current.send();});expect(x.result.current.session).not.toBeNull();await x.rerender({value:{...draft,financialQrMediaId:'qr-b'}});expect(x.result.current.session).toBeNull();await expect(x.result.current.confirm('123456')).rejects.toThrow('Vui lòng gửi lại');expect(mockUpdate).not.toHaveBeenCalled();});
it('a challenge for one account cannot confirm another',async()=>{const x=await renderHook<ReturnType<typeof useBankAccountOtpFlow>,{id:string}>(({id})=>useBankAccountOtpFlow(id,draft),{initialProps:{id:'A'}});await act(async()=>{await x.result.current.send();});await x.rerender({id:'B'});await expect(x.result.current.confirm('123456')).rejects.toThrow();expect(mockUpdate).not.toHaveBeenCalled();});
it('a late challenge response cannot restore an obsolete QR draft',async()=>{let resolve!:(value:any)=>void;mockRequest.mockReturnValue(new Promise(r=>{resolve=r;}));const x=await renderHook<ReturnType<typeof useBankAccountOtpFlow>,{value:typeof draft}>(({value})=>useBankAccountOtpFlow('A',value),{initialProps:{value:draft}});let request!:Promise<unknown>;await act(()=>{request=x.result.current.send();});await x.rerender({value:{...draft,financialQrMediaId:'qr-b'}});await act(async()=>{resolve({maskedEmail:'u***@example.test'});await request;});expect(x.result.current.session).toBeNull();});
