import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { ArrowLeft, BellRing, Plus } from 'lucide-react-native';
import React from 'react';
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BrandColors, Radius, Shadows, Spacing, Typography } from '../../../constants/theme';
import { adminNotificationService } from '../../../services/adminNotificationService';

const audienceLabel: Record<string, string> = { All: 'Tất cả người dùng', Customer: 'Customer', MUA: 'MUA', SelectedUsers: 'Người dùng đã chọn' };

export default function AdminNotificationsScreen() {
  const query = useQuery({ queryKey: ['admin', 'notification-campaigns'], queryFn: () => adminNotificationService.getCampaigns() });
  return <SafeAreaView style={styles.safe} edges={['top', 'left', 'right']}><View style={styles.screen}>
    <View style={styles.header}><TouchableOpacity style={styles.round} onPress={()=>router.back()}><ArrowLeft size={23} color={BrandColors.textDark}/></TouchableOpacity><View style={styles.heading}><Text style={styles.title}>Thông báo</Text><Text style={styles.sub}>Lịch sử thông báo đã gửi</Text></View><TouchableOpacity style={styles.add} onPress={()=>router.push('/(admin)/notifications/new' as never)}><Plus size={20} color="#FFF"/><Text style={styles.addText}>Tạo mới</Text></TouchableOpacity></View>
    {query.isLoading?<ActivityIndicator style={styles.loader} color={BrandColors.accentPink}/>:<FlatList data={query.data?.items??[]} keyExtractor={x=>x.id} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={query.refetch} tintColor={BrandColors.accentPink}/>} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><BellRing size={40} color={BrandColors.accentPink}/><Text style={styles.emptyTitle}>Chưa có thông báo</Text><Text style={styles.sub}>Thông báo admin đã gửi sẽ xuất hiện tại đây.</Text></View>} renderItem={({item})=><View style={styles.card}><View style={styles.cardTop}><View style={styles.icon}><BellRing size={21} color={BrandColors.accentPink}/></View><View style={styles.copy}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.meta}>{audienceLabel[item.audience]??item.audience} · {item.recipientCount} người nhận</Text></View><View style={styles.status}><Text style={styles.statusText}>Đã gửi</Text></View></View><Text style={styles.body}>{item.body}</Text><Text style={styles.time}>{new Date(item.createdAt).toLocaleString('vi-VN')}</Text></View>} />}
  </View></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BrandColors.bgPrimary},screen:{flex:1,width:'100%',maxWidth:760,alignSelf:'center'},header:{flexDirection:'row',alignItems:'center',padding:Spacing.md,gap:10},round:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF'},heading:{flex:1},title:{fontFamily:Typography.extraBold,fontSize:22,color:BrandColors.textDark},sub:{fontFamily:Typography.regular,fontSize:12,color:BrandColors.textSecondary,marginTop:2},add:{height:42,paddingHorizontal:13,borderRadius:21,flexDirection:'row',gap:6,alignItems:'center',backgroundColor:BrandColors.accentPink},addText:{fontFamily:Typography.bold,color:'#FFF',fontSize:13},loader:{marginTop:50},list:{padding:Spacing.base,paddingBottom:40,flexGrow:1},card:{backgroundColor:'#FFF',borderRadius:Radius.base,borderWidth:1,borderColor:BrandColors.borderLight,padding:Spacing.base,marginBottom:Spacing.sm,...Shadows.sm},cardTop:{flexDirection:'row',alignItems:'center',gap:10},icon:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center',backgroundColor:BrandColors.bgPink},copy:{flex:1},cardTitle:{fontFamily:Typography.bold,fontSize:16,color:BrandColors.textDark},meta:{fontFamily:Typography.regular,fontSize:12,color:BrandColors.textSecondary,marginTop:3},status:{backgroundColor:BrandColors.statusConfirmedBg,paddingHorizontal:8,paddingVertical:4,borderRadius:20},statusText:{fontFamily:Typography.bold,fontSize:10,color:BrandColors.statusConfirmed},body:{fontFamily:Typography.regular,fontSize:13,lineHeight:19,color:BrandColors.textBody,marginTop:12},time:{fontFamily:Typography.regular,fontSize:11,color:BrandColors.textMuted,marginTop:10},empty:{flex:1,alignItems:'center',justifyContent:'center',gap:9,paddingBottom:80},emptyTitle:{fontFamily:Typography.bold,fontSize:17,color:BrandColors.textDark}});
