import React, { useState } from 'react';
import { Alert, ActivityIndicator, StyleSheet, Text, TouchableOpacity, View, FlatList } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ArrowLeft, Building2, Pencil, Plus, Trash2 } from 'lucide-react-native';
import { useRouter } from 'expo-router';
import { BrandColors, Radius, Spacing, Typography } from '../../constants/theme';
import { useDeleteMuaBankAccount, useMuaBankAccounts } from '../../hooks/useMuaPayouts';
import { getApiError } from '../../services/api';
import { ConfirmDialog } from '../../components/common/ConfirmDialog';

export default function BankAccountsScreen(){const router=useRouter();const query=useMuaBankAccounts();const remove=useDeleteMuaBankAccount();const [deleteId,setDeleteId]=useState<string|null>(null);const confirmDelete=async()=>{if(!deleteId||remove.isPending)return;try{await remove.mutateAsync(deleteId);setDeleteId(null);}catch(error){Alert.alert('Không thể xóa',getApiError(error).message);}};const edit=(item:any)=>router.push({pathname:'/(mua)/bank-account-form',params:{id:item.id,bankCode:item.bankCode,bankName:item.bankName||'',holder:item.accountHolderName,isDefault:String(item.isDefault)}} as any);return <SafeAreaView style={styles.safe} edges={['top']}><View style={styles.header}><TouchableOpacity style={styles.icon} onPress={()=>router.back()}><ArrowLeft size={23} color={BrandColors.textDark}/></TouchableOpacity><Text style={styles.title}>Tài khoản ngân hàng</Text><TouchableOpacity style={styles.icon} onPress={()=>router.push('/(mua)/bank-account-form' as any)}><Plus size={23} color={BrandColors.accentRose}/></TouchableOpacity></View>{query.isLoading?<ActivityIndicator style={{marginTop:40}} color={BrandColors.accentRose}/>:query.isError?<Text style={styles.error}>{getApiError(query.error).message}</Text>:<FlatList data={query.data||[]} keyExtractor={x=>x.id} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><Building2 size={35} color={BrandColors.textMuted}/><Text style={styles.emptyText}>Chưa có tài khoản nhận tiền.</Text><TouchableOpacity style={styles.add} onPress={()=>router.push('/(mua)/bank-account-form' as any)}><Text style={styles.addText}>Thêm tài khoản</Text></TouchableOpacity></View>} renderItem={({item})=><View style={styles.card}><View style={{flex:1}}><View style={styles.row}><Text style={styles.bank}>{item.bankName||item.bankCode}</Text>{item.isDefault?<Text style={styles.default}>Mặc định</Text>:null}</View><Text style={styles.number}>{item.maskedAccountNumber}</Text><Text style={styles.holder}>{item.accountHolderName}</Text></View><TouchableOpacity style={styles.delete} onPress={()=>edit(item)}><Pencil size={18} color={BrandColors.accentRose}/></TouchableOpacity><TouchableOpacity style={styles.delete} onPress={()=>setDeleteId(item.id)} disabled={remove.isPending}><Trash2 size={19} color={BrandColors.statusCancelled}/></TouchableOpacity></View>}/>}<ConfirmDialog visible={Boolean(deleteId)} title="Xóa tài khoản" message="Tài khoản sẽ không còn được dùng cho các yêu cầu rút tiền mới." confirmLabel="Xóa" destructive loading={remove.isPending} onCancel={()=>setDeleteId(null)} onConfirm={confirmDelete}/></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BrandColors.bgPrimary},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:Spacing.md},icon:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontFamily:Typography.bold,fontSize:20,color:BrandColors.textDark},list:{padding:Spacing.base,flexGrow:1},card:{flexDirection:'row',alignItems:'center',backgroundColor:'#FFF',borderWidth:1,borderColor:BrandColors.borderLight,borderRadius:Radius.md,padding:Spacing.md,marginBottom:Spacing.sm},row:{flexDirection:'row',alignItems:'center',gap:8},bank:{fontFamily:Typography.bold,fontSize:16,color:BrandColors.textDark},default:{fontFamily:Typography.bold,fontSize:10,color:BrandColors.statusConfirmed,backgroundColor:BrandColors.statusConfirmedBg,paddingHorizontal:8,paddingVertical:3,borderRadius:Radius.full},number:{fontFamily:Typography.bold,fontSize:15,color:BrandColors.textBody,marginTop:7},holder:{fontFamily:Typography.regular,fontSize:12,color:BrandColors.textSecondary,marginTop:3},delete:{width:42,height:42,alignItems:'center',justifyContent:'center'},empty:{alignItems:'center',justifyContent:'center',paddingTop:80},emptyText:{fontFamily:Typography.regular,color:BrandColors.textMuted,marginVertical:Spacing.md},add:{backgroundColor:BrandColors.accentRose,borderRadius:Radius.full,paddingHorizontal:20,paddingVertical:12},addText:{fontFamily:Typography.bold,color:'#FFF'},error:{margin:Spacing.base,padding:Spacing.md,color:BrandColors.statusCancelled,backgroundColor:BrandColors.statusCancelledBg,borderRadius:Radius.md}});
