import React from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ArrowLeft, Building2, ChevronRight } from 'lucide-react-native';
import { useRouter } from 'expo-router';
import { BrandColors, Radius, Spacing, Typography } from '../../constants/theme';
import { useEarningsSnapshot } from '../../hooks/useMuaBookings';
import { useMuaPayouts } from '../../hooks/useMuaPayouts';
import { getApiError } from '../../services/api';

const money=(value:number)=>`${Math.max(0,value).toLocaleString('vi-VN')}đ`;
const labels:Record<string,string>={PENDING:'Đã gửi yêu cầu',MANUAL_ACTION_REQUIRED:'Chờ xử lý',PROCESSING:'Đang chuyển khoản',PAID:'Đã chi trả',FAILED:'Thất bại',UNKNOWN:'Đang kiểm tra'};

export default function MuaEarningsScreen(){
  const router=useRouter();const earnings=useEarningsSnapshot('me');const payouts=useMuaPayouts();
  const refreshing=earnings.isRefetching||payouts.isRefetching;
  const refresh=()=>{void earnings.refetch();void payouts.refetch();};
  return <SafeAreaView style={styles.safe} edges={['top']}><View style={styles.header}><TouchableOpacity style={styles.back} onPress={()=>router.back()}><ArrowLeft size={23} color={BrandColors.textDark}/></TouchableOpacity><Text style={styles.title}>Thu nhập & rút tiền</Text><TouchableOpacity style={styles.back} onPress={()=>router.push('/(mua)/bank-accounts' as any)}><Building2 size={21} color={BrandColors.accentRose}/></TouchableOpacity></View>
    <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>}>
      {earnings.isLoading?<ActivityIndicator color={BrandColors.accentRose}/>:earnings.isError?<ErrorText text={getApiError(earnings.error).message}/>:earnings.data?<><View style={styles.balance}><Text style={styles.balanceLabel}>Có thể rút</Text><Text style={styles.balanceValue}>{money(earnings.data.availableTotal)}</Text><View style={styles.totals}><Small label="Đang giữ" value={earnings.data.onHoldTotal}/><Small label="Đang xử lý" value={earnings.data.payoutPendingTotal}/><Small label="Đã chi trả" value={earnings.data.paidOutTotal}/></View></View><TouchableOpacity style={[styles.withdraw,earnings.data.availableTotal<=0&&styles.disabled]} disabled={earnings.data.availableTotal<=0} onPress={()=>router.push('/(mua)/withdraw' as any)}><Text style={styles.withdrawText}>{earnings.data.availableTotal>0?'Rút toàn bộ số dư khả dụng':'Chưa có số dư có thể rút'}</Text></TouchableOpacity></>:null}
      <Text style={styles.section}>Lịch sử chi trả</Text>
      {payouts.isLoading?<ActivityIndicator color={BrandColors.accentRose}/>:payouts.isError?<ErrorText text={getApiError(payouts.error).message}/>:!payouts.data?.length?<Text style={styles.empty}>Bạn chưa có yêu cầu rút tiền.</Text>:payouts.data.map(item=><TouchableOpacity key={item.id} style={styles.card} onPress={()=>router.push({pathname:'/(mua)/payouts/[id]',params:{id:item.id}} as any)}><View><Text style={styles.cardAmount}>{money(item.amount)}</Text><Text style={styles.meta}>{item.bankName||item.bankCode} · {item.maskedAccountNumber}</Text><Text style={styles.meta}>{new Date(item.createdAt).toLocaleString('vi-VN')}</Text></View><View style={styles.right}><Text style={styles.status}>{labels[item.status]}</Text><ChevronRight size={18} color={BrandColors.textMuted}/></View></TouchableOpacity>)}
    </ScrollView></SafeAreaView>;
}
function Small({label,value}:{label:string;value:number}){return <View style={{flex:1}}><Text style={styles.smallLabel}>{label}</Text><Text style={styles.smallValue}>{money(value)}</Text></View>}
function ErrorText({text}:{text:string}){return <Text style={styles.error}>{text}</Text>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BrandColors.bgPrimary},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:Spacing.md},back:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontFamily:Typography.bold,fontSize:20,color:BrandColors.textDark},content:{padding:Spacing.base,paddingBottom:Spacing.xxl},balance:{backgroundColor:BrandColors.accentRose,borderRadius:Radius.lg,padding:Spacing.lg},balanceLabel:{fontFamily:Typography.medium,color:'#FFEAF0'},balanceValue:{fontFamily:Typography.extraBold,fontSize:32,color:'#FFF',marginTop:4},totals:{flexDirection:'row',borderTopWidth:1,borderTopColor:'rgba(255,255,255,.3)',marginTop:Spacing.lg,paddingTop:Spacing.md,gap:8},smallLabel:{fontFamily:Typography.regular,fontSize:11,color:'#FFEAF0'},smallValue:{fontFamily:Typography.bold,fontSize:13,color:'#FFF',marginTop:3},withdraw:{minHeight:52,borderRadius:Radius.full,backgroundColor:BrandColors.textDark,alignItems:'center',justifyContent:'center',marginTop:Spacing.md},withdrawText:{fontFamily:Typography.bold,color:'#FFF'},disabled:{opacity:.45},section:{fontFamily:Typography.bold,fontSize:18,color:BrandColors.textDark,marginTop:Spacing.xl,marginBottom:Spacing.md},card:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:'#FFF',borderRadius:Radius.md,borderWidth:1,borderColor:BrandColors.borderLight,padding:Spacing.md,marginBottom:Spacing.sm},cardAmount:{fontFamily:Typography.bold,fontSize:17,color:BrandColors.textDark},meta:{fontFamily:Typography.regular,fontSize:12,color:BrandColors.textSecondary,marginTop:3},right:{alignItems:'flex-end',gap:9},status:{fontFamily:Typography.bold,fontSize:12,color:BrandColors.accentRose},empty:{fontFamily:Typography.regular,color:BrandColors.textMuted,textAlign:'center',padding:Spacing.xl},error:{fontFamily:Typography.semiBold,color:BrandColors.statusCancelled,padding:Spacing.md,backgroundColor:BrandColors.statusCancelledBg,borderRadius:Radius.md}});
