import * as ImagePicker from 'expo-image-picker';
import { useRouter } from 'expo-router';
import { ArrowLeft, ImagePlus, ShieldCheck } from 'lucide-react-native';
import React, { useState } from 'react';
import { ActivityIndicator, Alert, Image, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BrandColors, Radius, Spacing, Typography } from '../../constants/theme';
import { useSaveMuaIdentity } from '../../hooks/useMuaEligibility';
import { getApiError } from '../../services/api';
import { uploadImage } from '../../services/supabase';

type Field='identityFrontUrl'|'identityBackUrl'|'portraitUrl';
export default function IdentityVerificationScreen(){
 const router=useRouter(), save=useSaveMuaIdentity();
 const [images,setImages]=useState<Record<Field,string>>({identityFrontUrl:'',identityBackUrl:'',portraitUrl:''});
 const pick=async(field:Field)=>{const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)return Alert.alert('Cần quyền truy cập ảnh','Hãy cho phép ứng dụng chọn ảnh xác minh.');const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.9,allowsEditing:false});if(!result.canceled&&result.assets[0])setImages(current=>({...current,[field]:result.assets[0].uri}));};
 const submit=async()=>{if(Object.values(images).some(value=>!value))return Alert.alert('Chưa đủ ảnh','Vui lòng thêm CCCD/CMND mặt trước, mặt sau và ảnh chân dung.');try{const [identityFrontUrl,identityBackUrl,portraitUrl]=await Promise.all([uploadImage(images.identityFrontUrl),uploadImage(images.identityBackUrl),uploadImage(images.portraitUrl)]);await save.mutateAsync({identityFrontUrl,identityBackUrl,portraitUrl,certificateUrls:[]});if(Platform.OS==='web'){Alert.alert('Đã lưu','Thông tin xác minh đã được cập nhật.');router.replace('/mua-onboarding/setup');}else{Alert.alert('Đã lưu','Thông tin xác minh đã được cập nhật.',[{text:'Tiếp tục',onPress:()=>router.replace('/mua-onboarding/setup')}]);}}catch(error){Alert.alert('Không thể lưu',getApiError(error).message);}};
 const picker=(label:string,field:Field,helper:string)=><View style={s.group}><Text style={s.label}>{label}</Text><TouchableOpacity style={s.picker} onPress={()=>pick(field)}>{images[field]?<Image source={{uri:images[field]}} style={s.preview}/>:<ImagePlus size={26} color={BrandColors.accentRose}/>}<View style={{flex:1}}><Text style={s.pickTitle}>{images[field]?'Thay ảnh':'Chọn ảnh'}</Text><Text style={s.helper}>{helper}</Text></View></TouchableOpacity></View>;
 return <SafeAreaView style={s.safe} edges={['top','bottom']}><View style={s.header}><TouchableOpacity style={s.icon} onPress={()=>router.back()}><ArrowLeft size={23} color={BrandColors.textDark}/></TouchableOpacity><Text style={s.title}>Xác minh danh tính</Text><View style={s.icon}/></View><ScrollView contentContainerStyle={s.content}><View style={s.notice}><ShieldCheck size={24} color={BrandColors.accentRose}/><View style={{flex:1}}><Text style={s.noticeTitle}>Thông tin chỉ dành cho xét duyệt</Text><Text style={s.helper}>Giấy tờ không hiển thị công khai trên marketplace.</Text></View></View><View style={s.card}>{picker('CCCD/CMND mặt trước','identityFrontUrl','Ảnh rõ nét, đủ bốn góc')}{picker('CCCD/CMND mặt sau','identityBackUrl','Không lóa hoặc che thông tin')}{picker('Ảnh chân dung','portraitUrl','Ảnh chính diện, rõ khuôn mặt')}</View></ScrollView><View style={s.footer}><TouchableOpacity disabled={save.isPending} style={[s.button,save.isPending&&s.disabled]} onPress={submit}>{save.isPending?<ActivityIndicator color="#FFF"/>:<Text style={s.buttonText}>Lưu xác minh</Text>}</TouchableOpacity></View></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BrandColors.bgPrimary},header:{height:60,paddingHorizontal:Spacing.md,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:1,borderBottomColor:BrandColors.borderLight},icon:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontFamily:Typography.bold,fontSize:18,color:BrandColors.textDark},content:{width:'100%',maxWidth:700,alignSelf:'center',padding:Spacing.base,gap:Spacing.md},notice:{padding:Spacing.base,borderRadius:Radius.base,backgroundColor:BrandColors.bgPinkLight,flexDirection:'row',gap:12,alignItems:'center'},noticeTitle:{fontFamily:Typography.bold,fontSize:14,color:BrandColors.textDark},helper:{fontFamily:Typography.regular,fontSize:12,lineHeight:18,color:BrandColors.textMuted,marginTop:3},card:{padding:Spacing.base,borderRadius:Radius.base,backgroundColor:'#FFF',borderWidth:1,borderColor:BrandColors.borderLight},group:{marginBottom:Spacing.base},label:{fontFamily:Typography.semiBold,fontSize:14,color:BrandColors.textDark,marginBottom:7},picker:{minHeight:86,borderWidth:1,borderColor:BrandColors.borderLight,borderRadius:Radius.md,padding:10,flexDirection:'row',alignItems:'center',gap:12},preview:{width:72,height:58,borderRadius:Radius.sm},pickTitle:{fontFamily:Typography.bold,color:BrandColors.accentRose},footer:{padding:12,backgroundColor:'#FFF',borderTopWidth:1,borderTopColor:BrandColors.borderLight},button:{width:'100%',maxWidth:560,alignSelf:'center',minHeight:50,borderRadius:Radius.md,backgroundColor:BrandColors.accentRose,alignItems:'center',justifyContent:'center'},buttonText:{fontFamily:Typography.bold,color:'#FFF'},disabled:{opacity:.5}});
