import React, { useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { ArrowLeft, Clock3 } from 'lucide-react-native';
import { BrandColors, Radius, Spacing, Typography } from '../../constants/theme';
import { useMuaSchedule } from '../../hooks/useMuaSchedule';
import type { WorkingSchedule } from '../../services/muaScheduleService';
import { ErrorView } from '../../components/ui/ErrorView';

const days = ['Chủ nhật','Thứ 2','Thứ 3','Thứ 4','Thứ 5','Thứ 6','Thứ 7'];
const defaults = (): WorkingSchedule[] => days.map((_,dayOfWeek)=>({dayOfWeek,startTime:'09:00:00',endTime:'18:00:00',isActive:dayOfWeek>0&&dayOfWeek<6}));
const displayTime = (value:string) => value.slice(0,5);
const apiTime = (value:string) => /^\d{2}:\d{2}$/.test(value) ? `${value}:00` : value;

export default function WorkingHoursScreen(){
  const router=useRouter();
  const {data,isLoading,isError,refetch,save,isSaving}=useMuaSchedule();
  if(isLoading)return <SafeAreaView style={styles.center}><ActivityIndicator color={BrandColors.accentRose}/><Text style={styles.muted}>Đang tải lịch làm việc...</Text></SafeAreaView>;
  if(isError||!data)return <SafeAreaView style={styles.center}><ErrorView message="Không thể tải lịch làm việc" onRetry={refetch}/></SafeAreaView>;
  return <ScheduleEditor initial={data.workingSchedules} save={save} isSaving={isSaving} onBack={()=>router.back()}/>;
}

function ScheduleEditor({initial,save,isSaving,onBack}:{initial:WorkingSchedule[];save:(value:WorkingSchedule[])=>Promise<unknown>;isSaving:boolean;onBack:()=>void}){
  const byDay=new Map(initial.map(x=>[x.dayOfWeek,x]));
  const [schedule,setSchedule]=useState<WorkingSchedule[]>(()=>defaults().map(item=>byDay.get(item.dayOfWeek)||item));
  const [error,setError]=useState('');
  const update=(day:number,patch:Partial<WorkingSchedule>)=>{setSchedule(current=>current.map(x=>x.dayOfWeek===day?{...x,...patch}:x));setError('');};
  const handleSave=async()=>{const invalid=schedule.some(x=>x.isActive&&(!/^([01]\d|2[0-3]):[0-5]\d$/.test(displayTime(x.startTime))||!/^([01]\d|2[0-3]):[0-5]\d$/.test(displayTime(x.endTime))||displayTime(x.startTime)>=displayTime(x.endTime)));if(invalid){setError('Giờ làm việc chưa hợp lệ. Giờ kết thúc phải sau giờ bắt đầu.');return;}try{await save(schedule.map(x=>({...x,startTime:apiTime(displayTime(x.startTime)),endTime:apiTime(displayTime(x.endTime))})));onBack();}catch(e:any){setError(e?.response?.data?.message||e?.response?.data?.Message||'Không thể lưu lịch làm việc.');}};
  return <SafeAreaView style={styles.safe} edges={['top','bottom']}><View style={styles.header}><TouchableOpacity onPress={onBack} style={styles.iconButton} accessibilityLabel="Quay lại"><ArrowLeft size={23} color={BrandColors.textDark}/></TouchableOpacity><Text style={styles.headerTitle}>Lịch làm việc</Text><View style={styles.iconButton}/></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.intro}><Clock3 size={22} color={BrandColors.accentRose}/><View style={{flex:1}}><Text style={styles.introTitle}>Thời gian có thể nhận khách</Text><Text style={styles.introText}>Bật những ngày bạn làm việc và nhập giờ theo định dạng 09:00.</Text></View></View><View style={styles.list}>{schedule.map((item,index)=><View key={item.dayOfWeek} style={[styles.day,index>0&&styles.border]}><View style={styles.dayTop}><Text style={styles.dayName}>{days[item.dayOfWeek]}</Text><Switch value={item.isActive} onValueChange={value=>update(item.dayOfWeek,{isActive:value})} trackColor={{false:BrandColors.borderSoft,true:BrandColors.borderPink}} thumbColor={item.isActive?BrandColors.accentRose:'#FFF'}/></View>{item.isActive?<View style={styles.timeRow}><TextInput value={displayTime(item.startTime)} onChangeText={value=>update(item.dayOfWeek,{startTime:value})} keyboardType="numbers-and-punctuation" maxLength={5} style={styles.timeInput}/><Text style={styles.arrow}>→</Text><TextInput value={displayTime(item.endTime)} onChangeText={value=>update(item.dayOfWeek,{endTime:value})} keyboardType="numbers-and-punctuation" maxLength={5} style={styles.timeInput}/></View>:<Text style={styles.off}>Nghỉ</Text>}</View>)}</View>{error?<Text style={styles.error}>{error}</Text>:null}<TouchableOpacity style={[styles.primary,isSaving&&styles.disabled]} disabled={isSaving} onPress={handleSave}>{isSaving?<ActivityIndicator color="#FFF"/>:<Text style={styles.primaryText}>Lưu lịch làm việc</Text>}</TouchableOpacity></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BrandColors.bgPrimary},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:BrandColors.bgPrimary},muted:{marginTop:10,color:BrandColors.textMuted},header:{height:58,paddingHorizontal:Spacing.md,backgroundColor:'#FFF',flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:BrandColors.borderLight},iconButton:{width:44,height:44,alignItems:'center',justifyContent:'center'},headerTitle:{fontFamily:Typography.bold,fontSize:18,color:BrandColors.textDark},content:{padding:Spacing.base,paddingBottom:Spacing.xxl},intro:{backgroundColor:BrandColors.bgPink,padding:Spacing.base,borderRadius:Radius.base,flexDirection:'row',gap:12,alignItems:'flex-start',marginBottom:Spacing.base},introTitle:{fontFamily:Typography.bold,fontSize:15,color:BrandColors.textDark},introText:{fontFamily:Typography.regular,fontSize:12,lineHeight:18,color:BrandColors.textBody,marginTop:3},list:{backgroundColor:'#FFF',borderRadius:Radius.base,borderWidth:1,borderColor:BrandColors.borderLight,overflow:'hidden'},day:{padding:Spacing.base},border:{borderTopWidth:1,borderTopColor:BrandColors.borderDivider},dayTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},dayName:{fontFamily:Typography.semiBold,fontSize:15,color:BrandColors.textDark},timeRow:{flexDirection:'row',alignItems:'center',gap:12,marginTop:12},timeInput:{width:92,minHeight:44,borderRadius:Radius.md,borderWidth:1,borderColor:BrandColors.borderLight,backgroundColor:BrandColors.bgPinkLight,textAlign:'center',fontFamily:Typography.bold,fontSize:15,color:BrandColors.textDark},arrow:{color:BrandColors.textMuted,fontSize:18},off:{fontFamily:Typography.regular,fontSize:13,color:BrandColors.textMuted,marginTop:5},error:{fontFamily:Typography.regular,fontSize:13,lineHeight:19,color:BrandColors.statusCancelled,marginTop:12},primary:{minHeight:52,borderRadius:Radius.base,backgroundColor:BrandColors.accentRose,alignItems:'center',justifyContent:'center',marginTop:Spacing.lg},disabled:{opacity:.6},primaryText:{fontFamily:Typography.bold,fontSize:15,color:'#FFF'}});
