import React from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ArrowLeft, CheckCircle2, Clock3, XCircle } from 'lucide-react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { BrandColors, Radius, Spacing, Typography } from '../../../constants/theme';
import { useMuaPayout } from '../../../hooks/useMuaPayouts';
import { getApiError } from '../../../services/api';

const money=(v:number)=>`${Math.max(0,v).toLocaleString('vi-VN')}đ`;
const config={PENDING:['Đã gửi yêu cầu',Clock3],MANUAL_ACTION_REQUIRED:['Chờ nhân viên xử lý',Clock3],PROCESSING:['Đang chuyển khoản',Clock3],PAID:['Đã chi trả',CheckCircle2],FAILED:['Chi trả thất bại',XCircle],UNKNOWN:['Đang kiểm tra',Clock3]} as const;
export default function MuaPayoutDetailScreen(){const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const query=useMuaPayout(String(id||''));if(query.isLoading)return <SafeAreaView style={styles.safe}><ActivityIndicator style={{marginTop:60}} color={BrandColors.accentRose}/></SafeAreaView>;if(query.isError||!query.data)return <SafeAreaView style={styles.safe}><Text style={styles.error}>{getApiError(query.error).message}</Text></SafeAreaView>;const p=query.data;const [label,Icon]=config[p.status];return <SafeAreaView style={styles.safe} edges={['top']}><View style={styles.header}><TouchableOpacity style={styles.back} onPress={()=>router.back()}><ArrowLeft size={23} color={BrandColors.textDark}/></TouchableOpacity><Text style={styles.title}>Chi tiết rút tiền</Text><View style={styles.back}/></View><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Icon size={34} color={p.status==='PAID'?BrandColors.statusConfirmed:p.status==='FAILED'?BrandColors.statusCancelled:BrandColors.accentRose}/><Text style={styles.status}>{label}</Text><Text style={styles.amount}>{money(p.amount)}</Text></View><Section title="Tài khoản nhận"><Row label="Ngân hàng" value={p.bankName||p.bankCode}/><Row label="Chủ tài khoản" value={p.accountHolderName}/><Row label="Số tài khoản" value={p.maskedAccountNumber}/></Section><Section title="Thông tin yêu cầu"><Row label="Ngày tạo" value={new Date(p.createdAt).toLocaleString('vi-VN')}/><Row label="Số khoản thu nhập" value={String(p.receivableIds.length)}/><Row label="Mã giao dịch" value={p.providerReference||'—'}/>{p.paidAt?<Row label="Ngày chi trả" value={new Date(p.paidAt).toLocaleString('vi-VN')}/>:null}</Section>{p.failureMessage?<Section title="Lý do thất bại"><Text style={styles.failure}>{p.failureMessage}</Text></Section>:null}<Text style={styles.id}>Mã yêu cầu: {p.id}</Text></ScrollView></SafeAreaView>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}
function Row({label,value}:{label:string;value:string}){return <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BrandColors.bgPrimary},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:Spacing.md},back:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontFamily:Typography.bold,fontSize:20,color:BrandColors.textDark},content:{padding:Spacing.base,paddingBottom:Spacing.xxl},hero:{alignItems:'center',backgroundColor:'#FFF',borderRadius:Radius.lg,padding:Spacing.xl,borderWidth:1,borderColor:BrandColors.borderLight},status:{fontFamily:Typography.bold,color:BrandColors.textDark,marginTop:10},amount:{fontFamily:Typography.extraBold,fontSize:30,color:BrandColors.accentRose,marginTop:5},section:{backgroundColor:'#FFF',borderRadius:Radius.md,padding:Spacing.md,marginTop:Spacing.md,borderWidth:1,borderColor:BrandColors.borderLight},sectionTitle:{fontFamily:Typography.bold,fontSize:16,color:BrandColors.textDark,marginBottom:Spacing.sm},row:{flexDirection:'row',justifyContent:'space-between',gap:Spacing.md,paddingVertical:7},rowLabel:{fontFamily:Typography.regular,color:BrandColors.textSecondary},rowValue:{flex:1,fontFamily:Typography.semiBold,color:BrandColors.textDark,textAlign:'right'},failure:{fontFamily:Typography.regular,color:BrandColors.statusCancelled,lineHeight:20},id:{fontFamily:Typography.regular,fontSize:10,color:BrandColors.textMuted,textAlign:'center',marginTop:Spacing.lg},error:{margin:Spacing.base,padding:Spacing.md,color:BrandColors.statusCancelled,backgroundColor:BrandColors.statusCancelledBg,borderRadius:Radius.md}});
